### ISSUE TITLE
GS2: Why only one unknown?

### ISSUE THREAD

**Issue by caobo1994** [deemaalomair1/CAS741_project#11]
> Get the mass of one of unknown reactant.

I remember from the presentation that the reaction is limited to 2 reactants -> 2 reactants ones, but I do not see this constraint in your document. I assume that you have removed it.

In this case, why limit the kind of unknown reactant to one? From what I recall, after you have balanced the reaction, you only have to know one of the reactant to get the amount of others.

**Comment by deemaalomair1** [comment]
hello ,

no i did not remove it.. it is in the assumptions part.

so i will have one known reactant mass and one unknown reactant mass.

**Comment by smiths** [comment]
@deemaalomair1, this requirement will be clearer when you formalize it along the lines we have discussed.
