### ISSUE TITLE
NF1: Not sure it is non-functional

### ISSUE THREAD

**Issue by caobo1994** [deemaalomair1/CAS741_project#13]
> NF1: SMMP provides a correct Solution.

Not sure it is non-functional, since providing correct solutions is a essential function of this program.

**Comment by deemaalomair1** [comment]
I do not know .. but correctness could be one of non functional requirement also.
it is one of the needed Quilty.

**Comment by smiths** [comment]
Correctness is something that we want, but @caobo1994 is correct.  Correctness is defined as meeting the requirements.  It is implicit in having an SRS that you want it to be correct.  The corresponding non-functional requirement is accuracy.  How far away from the true solution are you allowed to be and still call the answer correct.

**Comment by deemaalomair1** [comment]
updated in 53ba5ef

**Comment by smiths** [comment]
@deemaalomair1, the linked commit hash is not related to the text of the nonfunctional requirements.  Did you mean a different commit?
