### ISSUE TITLE
Question about the 'User Responsibilities' 

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#16]
In the user responsibilities section, it said users should take care that consistent units are used for input variables.
Therefore, my understanding is that all the input variables should be in the same units. However, in the earlier section, it does not mention what kind of unit the system needs, so I assume that the system can automatically recognize the input unit. Please correct me if I misunderstood it!

 I feel like this might cause some confusion in the future, so I suggest the user should ensure the units of input variables have to satisfy the system requirement.
![image](https://user-images.githubusercontent.com/55363335/67115199-a9ae8800-f1ab-11e9-949c-03f23010f979.png)

**Comment by deemaalomair1** [comment]
i mean the user could not enter molecular weight for first reactant in a unit and molecular weight for second reactant in different unit.. because this will change the result

**Comment by smiths** [comment]
@deemaalomair1, the approach of expecting the user to use consistent units and then relying on the user to interpret the units of the output, is fairly standard in SCS (Scientific Computing Software).  This makes the software more flexible.  Of course, this only works if the calculations are unit agnostic.  If there is a conversion factor, or some dependence on a hard coded constant, then this doesn't work.

For the chemical reaction problem I think you are fine with leaving consistent units as the responsibility of the user.

I don't think there is anything to change here, so we'll close this issue.
