### ISSUE TITLE
Suggestion: Enhance the following content

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#17]
@deemaalomair1 
In the Physical System Description, I felt the explanation of the physical system could be more explicit.
For instance, in "PS1: Reactants mass",  you might like to make a clear statement of which "mass"  you were pointing out because, in figure 2, there were four squares labeled in mass.

![image](https://user-images.githubusercontent.com/55363335/67119906-221a4680-f1b6-11e9-8a15-dcca082355f4.png)

**Comment by sharyuwu** [comment]
@deemaalomair1 

Also maybe you should explain what "an unbalanced chemical reaction with sets of reactants and products" means by describing the contains of reactants and products.
Maybe it has contained a mass, a mole ratio or other elements?
And after you make a clear statement of this, you can also put it into the input of IM1!

![image](https://user-images.githubusercontent.com/55363335/67121034-8a6a2780-f1b8-11e9-90f4-10e8740be6f9.png)

![image](https://user-images.githubusercontent.com/55363335/67121663-0add5800-f1ba-11e9-9053-b01989f6bd1a.png)

**Comment by deemaalomair1** [comment]
yes i could add more details to the physical figure .
for second one , reactant or product are chemical element off course they will have a mass. but mole ratio is different thing i will calculate it my self.

**Comment by smiths** [comment]
@sharyuwu, I think your confusion will be removed when @deemaalomair1 formalizes the requirements.  Also, as I mentioned elsewhere, try to keep your issues to one "issue."

I suggest that we keep this issue open, and once the SRS has been updated, assign to @sharyuwu to see if the new documentation is more logical.

**Comment by deemaalomair1** [comment]
new SRS is available here : 

https://github.com/deemaalomair1/CAS741_project/blob/master/docs/SRS/SRS.pdf
