### ISSUE TITLE
Missing cross-reference

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#18]
@deemaalomair1 
Missing the cross-reference for Assumption.
Should add the cross-reference telling readers the relationship between the assumption and the Models( theoretical model [T], general definition [GD], data definition  [DD], instance model [IM])

![image](https://user-images.githubusercontent.com/55363335/67129707-5baa7c00-f1cd-11e9-8430-7a326468057b.png)

**Comment by sharyuwu** [comment]
It should be Table 4 instead of 4

![image](https://user-images.githubusercontent.com/55363335/67134848-4724ae80-f1e2-11e9-8473-9c2667dea0a9.png)

**Comment by deemaalomair1** [comment]
yes it should be Table 4 

but i did not get your point about cross-referencing of assumption ?

**Comment by smiths** [comment]
@sharyuwu, you can probably see why we want one issue per issue.  This conversation is now a mix of the discussion of Table 4 and the discussion of your first point.  @sharyuwu, I'm surprised that you didn't answer the question from @deemaalomair1.  You have a good point, if I understand you correctly, about the assumptions.

@deemaalomair1, what I believe @sharyuwu is getting at is that we document the traceability between the assumptions and the parts of the document that use each assumption.  After each assumption, you should list the chunks of the document that invoke that assumption.  For instance, if A1 is used by T1 and IM3, then after the text for A1, you would have the list [T1, IM3].  This gives you forward and backwards traceability throughout your document.  (I made up the relationship between A1, T1, etc., just for illustrative purposes.)

**Comment by sharyuwu** [comment]
@deemaalomair1 sorry about my late reply. 
And Thanks @smiths  helps me to answer deema's question.
Yes, what you reply is exactly what I meant.
@deemaalomair1  After adding traceability throughout the document, it is easier for readers to review your document.

**Comment by deemaalomair1** [comment]
update cross reference in commit 0095ee5d3d77f06fe5a2ecb647da71ec864e422e
