### ISSUE TITLE
Confused abbreviations

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#19]
@deemaalomair1 

The abbreviations of R and P had not explained clearly here.
Is R stand for reactants, reaction or requirement?
In your abbreviation table, you had put R as Requirement, so if the R here did not represent as Requirement, you should change the symbol.

![image](https://user-images.githubusercontent.com/55363335/67132590-3458ac80-f1d7-11e9-8d7f-b225ef9f94c7.png)

![image](https://user-images.githubusercontent.com/55363335/67132596-3d497e00-f1d7-11e9-985f-2723a4eb12d6.png)

**Comment by deemaalomair1** [comment]
yes i will change it and add abbreviation to the product also

thank you
