### ISSUE TITLE
Overlapping definition

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#20]
The definition of "m" was confusing to the reader of this document.
I can understand the mean of "m" by reading the following description, but it is all better to keep the definition consist.

I suggest to come up with a new symbol or a new abbreviation for the molecule.

![image](https://user-images.githubusercontent.com/55363335/67133117-74209380-f1d9-11e9-8050-02070c4a00cc.png)

Here is what I mean by overlapping definition
![image](https://user-images.githubusercontent.com/55363335/67133182-bcd84c80-f1d9-11e9-9c98-aa88d7c85ca1.png)

![image](https://user-images.githubusercontent.com/55363335/67133198-c6fa4b00-f1d9-11e9-9bf5-53cca2a206cf.png)

**Comment by deemaalomair1** [comment]
yes you are right .. i will change it 

thank you
