### ISSUE TITLE
The relationship between models

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#21]
@deemaalomair1 
Missing the reference from DD2 to DD3.
In the equation of DD3, it was using the definition of DD2.

![image](https://user-images.githubusercontent.com/55363335/67133545-4d635c80-f1db-11e9-89a7-6adda1f44a04.png)

![image](https://user-images.githubusercontent.com/55363335/67133590-826faf00-f1db-11e9-96bd-4ec354960bbb.png)

**Comment by deemaalomair1** [comment]
yes you are right.

thank you

**Comment by smiths** [comment]
@deemaalomair1,  you should include the commit hash for the edits that changes the document to address the issue.  That allows a future reader, including yourself, to know what changes were made.  The person creating the issue can review to make sure that their request has been adequately addressed.
