### ISSUE TITLE
Question about this equation

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#22]
@deemaalomair1 
I was confused about the description of the definition of IM1.
Is "Count the atoms of each side of the chemical reaction." means eq1 is one side of the chemical reaction and then eq2 is another side of the chemical reaction?
Please correct me if I misunderstand it.
If I have the right understanding, I suggest defining eq1 and eq2 explicitly in the document.

And also, the statement of "Use coeffcients; place them in front of the compounds as needed" make me feels ambiguous. I would like to know where did coeffcients come from, and when should I place the coeffcients in front of the compounds.

![image](https://user-images.githubusercontent.com/55363335/67133670-e3978280-f1db-11e9-85fe-b2bc4766c23f.png)

**Comment by deemaalomair1** [comment]
the chemical equation is like chemical reaction. i will take this reaction and divide it to two parts one for reactants side , other for products side. then i will apply chemicalEq_atoms count (eq1) for the first side which need to be equal to chemicalEq_atoms count (eq2) product sides. if you feel its confusing i can change the name of them to chemicalEq_atoms count (reactant_side), chemicalEq_atoms count (products_side).

coefficients is any number before any reactant or product. to balance the chemical reaction we need to change this number sometimes. we can add this number to balance the chemical reaction if it does not exist, or change it amount if it already exist.

**Comment by smiths** [comment]
I believe that the revisions to the SRS will help with making this clear.

**Comment by sharyuwu** [comment]
@smiths  Yes, it does make the content more clear. @deemaalomair1 I suggest adding "Daniel M. Homan and Paul A. Strooper. Software Design, Automated Testing, and Main-
tenance: A Practical Approach. International Thomson Computer Press, New York, NY,
USA, 1995. URL http://citeseer.ist.psu.edu/428727.html." in your reference document, so readers can know how this mathematical notation work.

**Comment by smiths** [comment]
@sharyuwu, that is good advice about the H&S reference.  @deemaalomair1, I suggest you do this (when you get back to school.)
