### ISSUE TITLE
Confused reference

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#23]
@deemaalomair1 
It did not look like IM1 was referred by DD5.

If they do refer to each other, do you mind to explain the relationship between them?

![image](https://user-images.githubusercontent.com/55363335/67134210-11ca9180-f1df-11e9-920b-bf371cdfd5d8.png)

**Comment by deemaalomair1** [comment]
after balancing the chemical reaction new coefficient will be resulted. these coefficients of reactant 1 ,2  will be used to get the mole ratio by the equation : coefficientofR2 / coefficientofR1

**Comment by smiths** [comment]
@deemaalomair1, the data definitions shouldn't reference the instance models.  The proper relationship is the other way around.  The IMs use the DDs, not the other way around.  This might be a clue that the classification of your "chunks" (parts of knowledge) need to be revised.

**Comment by deemaalomair1** [comment]
has been updated in the new SRS : 

https://github.com/deemaalomair1/CAS741_project/tree/master/docs/SRS
