### ISSUE TITLE
Question abut the input value

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#24]
@deemaalomair1 
Was molecular weight(mv) an input value?
Based on the document, we can get molecular weight(mv) from the date definition DD4. Therefore, I was wondering that shouldn't the input value be atomic weights and molecule atoms.

@smiths if we could get your opinion on this, I'd appreciate it!

![image](https://user-images.githubusercontent.com/55363335/67134511-8b16b400-f1e0-11e9-9c0e-38acf7781c9f.png)

![image](https://user-images.githubusercontent.com/55363335/67134809-23616880-f1e2-11e9-9510-57604960fb78.png)

**Comment by deemaalomair1** [comment]
yes it is input by the user

**Comment by deemaalomair1** [comment]
i just put it's equation as DD because it may be calculated by the program later on.
see likely changes section

**Comment by smiths** [comment]
@sharyuwu, I believe that the calculation of molecular weight will be easier to understand when @deemaalomair1 completes her revision of the SRS to make it more formal.  I don't think there is any task left to be done for this issue, so I'll close it.
