### ISSUE TITLE
Improve Mathematical Model in SRS

### ISSUE THREAD

**Issue by smiths** [deemaalomair1/CAS741_project#25]
@deemaalomair1, your SRS only partially follows the mathematical approach that I laid out for you.  I assume that is because you didn't quite understand what I was getting at.  The goal is to build an abstract model of a chemical reaction and then use that model to express specific, unambiguous, requirements.  The model I laid out for you may not have been complete enough for you to see where it was going, so I have completed a more detailed (but still incomplete) version.  I will attach a scan of what I have come up with to this post.  Please use this information to revise your SRS.  If you have any questions, please ask.
![Page1](https://user-images.githubusercontent.com/1422000/67205296-78b59980-f3dd-11e9-8c3d-0ea304498abf.jpg)
![Page2](https://user-images.githubusercontent.com/1422000/67205318-8408c500-f3dd-11e9-9143-4fed6562eb6d.jpg)
![Page3](https://user-images.githubusercontent.com/1422000/67205327-8834e280-f3dd-11e9-932a-8745401c36f6.jpg)

**Comment by deemaalomair1** [comment]
hello Dr.Smiths
 do you mean by chemical Eq T = one side of the reaction? like NA + CL 
and reaction T is the full equation? NA + CL = NACL 

the type definition will be like this :
ElementT = set of elements = { He, H , ...}
MoleculeT = tuple of (number : N , element : ElementT).
CompoundT =  set of MoleculeT(element1, element2 : MoleculeT).
ChemicalEqT = set of CompoundT ( element1, element2 : CompoundT)
Reaction T = sequence [2] of ChemicalEqT.

i just would like to make sure i understand it correctly

**Comment by smiths** [comment]
@deemaalomair1,  yes the chemical Eq T is one side of the reaction and the ReactionT is the full equation.

Your type definitions are missing a number that you need.  You have a number with MoleculeT, which you can use for H_2, but you do not have anything that can provide a coefficient, like 2H_2.  I also don't know how to read your notation for CompoundT and Chemical EqT.

**Comment by deemaalomair1** [comment]
i have updated the document and included the mathematical model here:
https://github.com/deemaalomair1/CAS741_project/blob/master/docs/SRS/SRS.pdf
i did not change the traceability matrix yet.. i just want to make sure that my data definitions , instance models are correct first.

**Comment by smiths** [comment]
This is a good start @deemaalomair1.  It isn't exactly how I'd write it, but it is a big improvement.  After you complete your MIS, we should go back to look over your SRS again, to make sure the two documents are consistent.

We can close this issue now.
