### ISSUE TITLE
Page 3 - Input format

### ISSUE THREAD

**Issue by Ao99** [deemaalomair1/CAS741_project#27]
On page 3, in T2 and T3, the test input might need to be more specific.

Is H2O or H2O = 2 a string? Does it need to be typed in manually, or input through a file?
If it needs to be typed, it might be better to write just as "H2O" here.

**Comment by deemaalomair1** [comment]
updated  in commit : https://github.com/deemaalomair1/CAS741_project/commit/4fe6f458f4d28cb0328470efd9c3e97a31671d14
