### ISSUE TITLE
Page 3 - Input tests

### ISSUE THREAD

**Issue by Ao99** [deemaalomair1/CAS741_project#28]
You might need more input tests.

1. For example, testing only -7 might be not enough, what about 0?
2. Before testing the outputs, you might need 3 more tests showing that the software can take valid inputs correctly.
For example, if you get an error in the current T4 - result test, how can you be confident that the software takes all 3 inputs correctly?

**Comment by deemaalomair1** [comment]
i added a test to test the format of each reactant / or product entered by the user in commit : 
 https://github.com/deemaalomair1/CAS741_project/commit/7b7f5b4def4088512d31c0f9c2d369e2444dfe21

for testing the mass value range .. when user enter -7 or 0 the error message will show that the value must be greater than 0. also i have test to test the format of entire chemical reaction.
