### ISSUE TITLE
page 4 - output test

### ISSUE THREAD

**Issue by Ao99** [deemaalomair1/CAS741_project#29]
1. T4: in T1 it is only a number without unit, so here you might want to write "3.10" instead of "3.10 g"

2. You might need to specify again how do you input data - manually input string? or from a file?

3. One reaction per test might be not enough, you might want to test multiple reactions.

**Comment by deemaalomair1** [comment]
updated point 1 in commit: https://github.com/deemaalomair1/CAS741_project/commit/37427dd73dce478ddd67be6f02e48dad7a4b3179
point 2 : I am testing the output here not the input , so i think no matter from where i get the input the output should be correct. 
point 3: off course i will try it with multiple reaction .. but this is an example case.
