### ISSUE TITLE
The reference

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#32]
It is great that you provide a link to readers directly to the GitHub, but it will be even better if you also put a reference that refers to your SRS. Therefore, if the readers print your document out, they can still know where to find your SRS.

![image](https://user-images.githubusercontent.com/55363335/68998254-26518680-087e-11ea-8105-45cafb2365b7.png)

**Comment by deemaalomair1** [comment]
my SRS is only available at GitHub .. so it's the only source i can provide

**Comment by smiths** [comment]
@deemaalomair1, I believe that @sharyuwu was referring to creating a BibTeX entry for your SRS.  You can then cite it and it will appear in your list of References.  The citation can still include a URL, but it will be printed, as well as hyper-linked.

**Comment by deemaalomair1** [comment]
updated in commit 1d2aed1d3cdf36b201f6886def2be413e44b0f3a
