### ISSUE TITLE
The content of the objectives can be more abstract 

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#33]
I feel you are up to something good, but it will better if forming the content is a more abstract way.
For instance, state that the object of the document is to build the confidence of the correctness of the software, or enhance the maintainability for the traceability of the potential changes.
 
![image](https://user-images.githubusercontent.com/55363335/68998346-14bcae80-087f-11ea-86fe-cb6eb05dd6ce.png)

**Comment by deemaalomair1** [comment]
updated in commit 5b2c5cd9975b4a913ea791f21e7e02c97310ae81

thanks
