### ISSUE TITLE
Separate every point

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#34]
The first point of the Implementation Verification Plan has too much detail in it.
Dynamic testing and automatic testing can be separated into two different points. Moreover, leave the unit testing to the UnitVnVPlan does not mix them up together.

![image](https://user-images.githubusercontent.com/55363335/68999237-f6a97b00-088b-11ea-929b-e3c1ec961666.png)

**Comment by deemaalomair1** [comment]
updated in commit 533f70f9bfe0c4c786f4012a2dfcca5457f9a116
