### ISSUE TITLE
Confused statement

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#35]
I suggest making this statement more clear. Will the code walkthrough be carried out by a meeting? What the domain expert and Dr.Smith have to implement before the code walkthrough happens?

![image](https://user-images.githubusercontent.com/55363335/68999392-75eb7e80-088d-11ea-8392-d4c41d8632ee.png)

**Comment by deemaalomair1** [comment]
i thought about it again. i think i was misunderstand what walkthrough is. 

i decided not to include it in my testing anymore and i remove it from the list.
