### ISSUE TITLE
Suggestion need more explanation about the automatic unit testing

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#37]
I suggest giving more information about how the automatic unit testing plan to be carried out. Will it be implemented my input a file of data? Will the test cases start from Input = 0, which is the first invalid case?

![image](https://user-images.githubusercontent.com/55363335/68999704-599e1080-0892-11ea-8a27-b178ab736cd1.png)

**Comment by deemaalomair1** [comment]
i have change it in commit 747798ff32c46b230fb5622395682b7d0c3d17a6
