### ISSUE TITLE
Missing a figure

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#38]
The figure of Models' Relations should be in your SRS as the template arranged.

Your document
![image](https://user-images.githubusercontent.com/55363335/69000761-cb7e5600-08a2-11ea-8eba-1b7279683c17.png)

The missing figure
![image](https://user-images.githubusercontent.com/55363335/69000764-d6d18180-08a2-11ea-9948-9a122f08191b.png)

**Comment by smiths** [comment]
@sharyuwu, it isn't wrong to include this figure, but I think @deemaalomair1 can consider it optional.  I put it in the template for the purpose of teaching the relationship between the chunks of knowledge, not so much as an example of what should be conveyed to the SRS readers.
