### ISSUE TITLE
Suggestion of symbol

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#39]
I suggest using $\times$ instead of $X$

![image](https://user-images.githubusercontent.com/55363335/69000936-adb1f080-08a4-11ea-9e24-22908fc02d53.png)

**Comment by smiths** [comment]
I agree with @sharyuwu.  The use of mathematical mode in LaTeX should go even further than this.  For instance, all of the variables should be in italic font.  For instance, m, and e should be in italics.  From a formatting perspective, it will look better to put everything in an equation environment and use \text{} when something  uses a regular font.

**Comment by deemaalomair1** [comment]
updated in commit ca1f32593dde685d7f963625d33118c097849f29
