### ISSUE TITLE
MG/MIS submitted

### ISSUE THREAD

**Issue by deemaalomair1** [deemaalomair1/CAS741_project#42]
MG/MIS have been uploaded and ready to be reviewed. 

https://github.com/deemaalomair1/CAS741_project/tree/master/docs/Design

**Comment by smiths** [comment]
Comments on MG are available in 831db47.

**Comment by smiths** [comment]
I pushed one more commit (e037845) related to beginning the process of fixing the reference list for the MG document.

**Comment by smiths** [comment]
Comments on MIS available in 9d25631.

**Comment by deemaalomair1** [comment]
MG updated in commit f3bfc726e4cbe3a73e696373cc63103cd0005704
MIS updated in commit 7f27fe5fec88064f5488e5f63a14cbc8ca186820
