### ISSUE TITLE
MG 4.2 Unlikely Changes 

### ISSUE THREAD

**Issue by peter-michalski** [deemaalomair1/CAS741_project#43]
Is UC2 definite? I am wondering if this should be under this section, might be good to consider removing it. Will the current goal statement, such as GS2: Get the mass of one unknown reactant, definitely not change? Is it possible that SMMP evolves to get more than the mass of one reactant? Could more goal statements be added if the software evolves?

**Comment by deemaalomair1** [comment]
i do not think i will change the goal statement of my project let's say at least for the scope of the course. if someone else is interested in this project he can do some additional enhancement and modify the goal statement. right now i prefer to keep it under unchanged
