### ISSUE TITLE
MG 7.2.2  Atomic Mass Module Wording

### ISSUE THREAD

**Issue by peter-michalski** [deemaalomair1/CAS741_project#44]
"How to get the atomic mass for each chemical element from the library."

Is this a control algorithm? I think rewording this secret may be a good idea. It is not very clear what the secret is. Perhaps "The control algorithm for getting the atomic mass for..."

**Comment by deemaalomair1** [comment]
updated in commit ca969c37a49e99100617dd56e4db197e24173452.
thanks
