### ISSUE TITLE
MG 7.2.1 Input Module clarity

### ISSUE THREAD

**Issue by peter-michalski** [deemaalomair1/CAS741_project#45]
"The format and structure of the valid inputs plus the software constraints."

It sounds like a lot is happening here. Modules are supposed to be stand alone and generally not have "and". While you might be able to get away with "format and structure" you also have "plus the software constraints". It sounds like there might be several secrets that could be divided into separate modules. I am also wondering if perhaps some of the words above "format, structure, constraints" are redundant. What is the difference between them?

I looked into the MIS and it is not clear to me what the difference is. I suggest splitting up the above into separate modules, removing some of the wording, or clarifying what is meant by adding more information into the relevant section of the MIS.

**Comment by deemaalomair1** [comment]
i just mean one thing here. format of the valid inputs. so i updated the MG to be more clear in commit 9ee7b93ec54ab5ebc2c1d269488cca71d8818b80

thank you
