### ISSUE TITLE
MG: 9  Use Hierarchy Between Modules

### ISSUE THREAD

**Issue by peter-michalski** [deemaalomair1/CAS741_project#47]
The Use Hierarchy Among Modules graph is not clear to me. It looks like Input Module uses ReactionT Module and Mass Calculation Module; however, the MIS of the Input Module(M2) states that the module does not use any other module. It seems like the arrows of the DAG are backwards.

**Comment by deemaalomair1** [comment]
Hello peter , you are right. i just edited the graph in the commit 548a938518d6001d0442f8dc2f04c8dbdf27951b

thank you
