### ISSUE TITLE
function to implement 

### ISSUE THREAD

**Issue by deemaalomair1** [deemaalomair1/CAS741_project#48]
hello ,

i would like you to give a try in implementing Balance_reaction function. assume that the entered reaction is not balanced and need to be balanced by the program. if you could try this in python is better because i am using python to implement the project.

**Comment by sharyuwu** [comment]
Okay.
I will try my best to make it happened

**Comment by smiths** [comment]
@sharyuwu, are you going to try to implement the module?  If you try, even if you don't finish, I can give you some marks for the effort.

**Comment by sharyuwu** [comment]
Thank you for asking.
I plan to try it. But it hasn't happened yet.
Most likely it will happen today.

**Comment by sharyuwu** [comment]
Posted the progress of the implementation.

I have some questions regarding the secret behind this function. 
I feel the MIS document has not fully exposed the secret.
I have posted the issue in https://github.com/deemaalomair1/CAS741project/issues/49
