### ISSUE TITLE
Question About MIS: MIS of ReactionT Module

### ISSUE THREAD

**Issue by sharyuwu** [deemaalomair1/CAS741_project#49]
HI @deemaalomair1 
Do you mind to explain the transition for the Balanced-Reaction in MIS of ReactionT Module?

I see you have lots of local functions in this module but none of them is being used by Balanced-Reaction.
What do you mean by Reaction := Reaction*.
What is the  Reaction* here come from?
Is the Reaction denotes the state variable?
Maybe you have not updated the latest version of your documentation?

**Comment by deemaalomair1** [comment]
actually i just finished doing this module of the implementation.. i do not know if you still need to implement it or not ? @sharyuwu @smiths

**Comment by sharyuwu** [comment]
oh! I am sorry that I didn't follow your pace.
Congratulation on finishing this module!
Is there any module you have not done yet, and I can help you with it?

**Comment by smiths** [comment]
@sharyuwu, you don't need to worry if the module has already been implemented.  The other student pairs have both implemented the same modules.  It has been an interesting exercise to compare the two versions.

**Comment by deemaalomair1** [comment]
i have updated MIS and added more information about Reaction* , you can look up now and if you still do not feel comfortable you can ask again 
i will keep this issue open and i will close issue #48

**Comment by sharyuwu** [comment]
I am sorry there is still some part that I don't quite get it.
If MIS of ReactionT Module is an ADT file, for a suggestion the Module name is better to be MIS of ReactionT ADT Module.
So readers can know this module will create a new kind of data type.

**Comment by sharyuwu** [comment]
![image](https://user-images.githubusercontent.com/55363335/71313090-e132ee00-2401-11ea-9d20-9eb3f6d6cc11.png)
I see you have some explanation regarding to Reaction*.
However, I think there should be more information in Reaction* := Reaction
1. which side is the reaction side and which side is the product side.
2. how to calculate the appropriate coefficient?
You did explain what is this appropriate coefficient for but readers also need the information of how to get this number.

**Comment by deemaalomair1** [comment]
1. Reaction* and Reaction both of them are full chemical reaction , Reaction* after balancing , where Reaction before balancing.
2. how to get coefficient is the secret that i was not know how to calculate it when writing MIS document. ( this is the main idea of how to balance ) after implementing the system i got a way to get coefficients.
they could be calculated in different way depending on developer idea.

**Comment by sharyuwu** [comment]
----
1. Reaction* and Reaction both of them are full chemical reaction , Reaction* after balancing , where Reaction before balancing.

If this is the cases then I think the better approach will be  
Reaction = how to balance the reaction.
Because transition means that you are going to store some values in the state variables, my best guess is that you want to store the values that have been rebalanced inside the state variables.

----
2. how to get coefficient is the secret that i was not know how to calculate it when writing MIS document. ( this is the main idea of how to balance ) after implementing the system i got a way to get coefficients.
they could be calculated in different way depending on developer idea.

Great you have figured out how to calculate it. 
I still have an interest in implement this function. If you don't mind, do you want to update how you calculate this coefficient?
The purpose of MIS is to explicitly show how to implement the function so it is better to document it. Although the calculating can be done in diverse different ways.
