### ISSUE TITLE
2.1 PoD: Informal language

### ISSUE THREAD

**Issue by caobo1994** [deemaalomair1/CAS741_project#6]
> The SRS is abstract because the contents say what problem is being solved, but do not say how to solve it.

This sentence seems too causal for me, and it might not be suitable for this kind of scientific document.

**Comment by deemaalomair1** [comment]
I took this sentence from Software Requirements Specification for Solar Water
Heating Systems provided by Dr.Smith in Drasil project. I do not think it is causal.

**Comment by smiths** [comment]
@deemaalomair1, your text is fine in my opinion.   You are defining the meaning of abstract in this context.  Since no changes will be made as a result of this issue, we can close the issue.
