### ISSUE TITLE
3.1 System Context: Missing SMMP requirements regarding error message

### ISSUE THREAD

**Issue by caobo1994** [deemaalomair1/CAS741_project#8]
> Determine if the inputs satisfy the required physical and software constraints.

What happens if the inputs do not? I guess some error messages are necessary for users.

**Comment by deemaalomair1** [comment]
doI need to say that the system will show an error massage in SRS document ?

**Comment by smiths** [comment]
Yes, I think it is a good idea to have a verification requirement.  If the input does not match the expected format or content, then the user should be informed.  The specific text of the error message can wait until the design documentation, but a requirement for supplying an error message makes sense in the SRS.

**Comment by deemaalomair1** [comment]
i just added it.

**Comment by smiths** [comment]
@deemaalomair1, when you close an issue, please include the commit hash that closes the issue.

**Comment by deemaalomair1** [comment]
updated in 24f3ad4

**Comment by smiths** [comment]
@deemaalomair1, I'm not sure the commit you point to is the one that addresses the issue created by @caobo1994.  You may have meant a different commit?
